server:
  port: 8090

spring:
  datasource:
    username: root
    password: sa
    url: jdbc:mysql://192.168.2.139:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/UserMapper.xml
  type-aliases-package: com.springboot.dao
